@Web.API_HostAddress = https://localhost:7017

POST {{Web.API_HostAddress}}/auth
Accept: application/json
Content-Type: application/json

{
    "Username": "admin",
    "Password": "admin"
}

###

GET {{Web.API_HostAddress}}/WeatherForecast
Accept: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzg4NzM1ODMsIm5iZiI6MTc3ODg3MTc4MywiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImFkbWluIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWRtaW5AdGhpc05ld1NpdGUiLCJEZXBhcm1lbnQiOiJIUiIsIkFkbWluIjoidHJ1ZSIsIk1hbmFnZXIiOiJ0cnVlIiwiRW1wbG95bWVudERhdGUiOiIyMDI1LTA0LTAxIiwiaWF0IjoxNzc4ODcxNzgzfQ.RJjQ6kgwCCavH1vVtpex67cv8mDJq_Cjeda0I5OrqYY
Content-Type: application/json
